apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvmcluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - name: lvm
        fstype: ext4 
        default: true
        deviceSelector:
          paths:
            - /dev/disk/by-partlabel/lvm
          forceWipeDevicesAndDestroyAllData: true
        thinPoolConfig:
          name: thin-pool
          overprovisionRatio: 10
          sizePercent: 90
