apiVersion: v1
baseDomain: kmod.io
compute:
- architecture: amd64 
  hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
metadata:
  name: ocp 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.8.0/24
  networkType: OVNKubernetes 
  serviceNetwork:
  - 172.30.0.0/16
platform: 
  none: {}
pullSecret: '{"auths":{"laptop.kmod.io:8443": {"auth": "aW5pdDpZekRDOFRxOVVjNG9lajAyNjNsZnBXN1B3U0U1dGgxQQ=="}}}' 
sshKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC9LAGxa/nL7S3RKFCa31yLtqx+iZ6SJEihPomz1rK+iR/s7/BNofkvt3/fB66z95X5r0mkqtrcUx21EL/PkfXNe6dBoJmT2hkjG4LyeeHB7pjZSSToWUYJKss1tvWa1znQ1U+hTMLW/ohea29sOrZZX+OT1Gtfth3DKrh01VEosBQXtvxzMqpMy1ufrnlIwZjCKPFBrDrb66leWA37L/pfKDJljky+s2EqSHsnRlYUw8/oYYVrC6qGghtnjzRL1JSZfRwONZlbJwxk3azFVWpfKQYY3x9s0dHB5txjZszeOZZhmTMWWHgHTlPzjxgEliHwSOh1C5nqrqEHkdr8NqhwHURMuOJVbtvdOp8WGDiTqWKsDNqmQxnYfr1LIVPoF6qSz4zdr0r43CIrlttBSB09GJ8lGP+2i8Bzbs9JUJA5Z0oxz7P2uEJKLOUoN7mJ1eKdI3aLH9f/h8qhXEx5k86a1KPps6EKm/JPF761ttB6KV40MkOzSmB+OypvmcevBvk= ko@laptop.kmod.io'
imageDigestSources:
  - mirrors:
    - laptop.kmod.io:8443/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
  - mirrors:
    - laptop.kmod.io:8443/openshift/release-images
    source: quay.io/openshift-release-dev/ocp-release
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIID0DCCArigAwIBAgIUaRCcaxCoWFjMdUZ4o13DzEHlS6owDQYJKoZIhvcNAQEL
  BQAwaDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
  azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xFzAVBgNVBAMMDmxh
  cHRvcC5rbW9kLmlvMB4XDTI0MTEyMDIxNDczNVoXDTI3MDkxMDIxNDczNVowaDEL
  MAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9yazENMAsG
  A1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xFzAVBgNVBAMMDmxhcHRvcC5r
  bW9kLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06HBNt6oxHVP
  oq5sj2tHRZyLdiiUlalQZRYdXJMbU5qHYx0v/pXeZZBaj1xOR+bpvb8wKs4bxAPe
  12pKLHk2movOd/KUg6ijc8ASq+uJJQjAG2tQuC0hQaO/96VW0/6xMvxcYx2VBahD
  fxJMln4LLjZoar3+jjuHyFhPwHER+Qa+LvChQkUdPrBbZyeI0G4JMofvrsHHahG5
  AMQBeDwGcya0XxBpvDIj4kJJ0+AQPxWrvWwmVCK9z9vcReZjfu6/g1+6hhxarHDK
  wat8paQM8jfYuCW8PFMWbL+iOzpSBVB+theUnuJqfQjzq4kc51QbsRt1v6o4CvGc
  GKLyV6JTuwIDAQABo3IwcDALBgNVHQ8EBAMCAuQwEwYDVR0lBAwwCgYIKwYBBQUH
  AwEwGQYDVR0RBBIwEIIObGFwdG9wLmttb2QuaW8wEgYDVR0TAQH/BAgwBgEB/wIB
  ATAdBgNVHQ4EFgQUFam2JN9/9Xo7ebqMDMJZQSu/K2MwDQYJKoZIhvcNAQELBQAD
  ggEBAIWzvXQ8Xmd3mmLVnwxoRraQ3sFYIVYR+iQrTNBYwqsA/3HT0lQQyZKnOiso
  z7mQ3IeFeqkkuf/Ryh+oJIh+5wjwjjs8Qdnq8hKfcbBn3aY69cbwIUztcMC0cVlV
  6dHIb6OuJ9/1P+hXF+khvYpxDUBPUDZebKY9wasZg9c2A0UMWBhiZg4+pr8Lnnys
  ZoVpyltmFKdaH04u8QMut1Ha2dTP3/suTzLiiVVUnpW0Jc7hUMFhbm+pqiX8MbMo
  AFiQe0sbdPtlWtn7wOvJsS30LnEKg4Se0Ixw3A0hqUYg8CvxHpQd6N2QDrNa4ngP
  73MviqD9jU3a/SbDgxBtqdqQ9wU=
  -----END CERTIFICATE-----
