apiVersion: v1
kind: ConfigMap
metadata:
  name: mirror-registry
data:
  laptop.kmod.io..8443: |
    -----BEGIN CERTIFICATE-----
    MIID0DCCArigAwIBAgIUaRCcaxCoWFjMdUZ4o13DzEHlS6owDQYJKoZIhvcNAQEL
    BQAwaDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9y
    azENMAsGA1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xFzAVBgNVBAMMDmxh
    cHRvcC5rbW9kLmlvMB4XDTI0MTEyMDIxNDczNVoXDTI3MDkxMDIxNDczNVowaDEL
    MAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMREwDwYDVQQHDAhOZXcgWW9yazENMAsG
    A1UECgwEUXVheTERMA8GA1UECwwIRGl2aXNpb24xFzAVBgNVBAMMDmxhcHRvcC5r
    bW9kLmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA06HBNt6oxHVP
    oq5sj2tHRZyLdiiUlalQZRYdXJMbU5qHYx0v/pXeZZBaj1xOR+bpvb8wKs4bxAPe
    12pKLHk2movOd/KUg6ijc8ASq+uJJQjAG2tQuC0hQaO/96VW0/6xMvxcYx2VBahD
    fxJMln4LLjZoar3+jjuHyFhPwHER+Qa+LvChQkUdPrBbZyeI0G4JMofvrsHHahG5
    AMQBeDwGcya0XxBpvDIj4kJJ0+AQPxWrvWwmVCK9z9vcReZjfu6/g1+6hhxarHDK
    wat8paQM8jfYuCW8PFMWbL+iOzpSBVB+theUnuJqfQjzq4kc51QbsRt1v6o4CvGc
    GKLyV6JTuwIDAQABo3IwcDALBgNVHQ8EBAMCAuQwEwYDVR0lBAwwCgYIKwYBBQUH
    AwEwGQYDVR0RBBIwEIIObGFwdG9wLmttb2QuaW8wEgYDVR0TAQH/BAgwBgEB/wIB
    ATAdBgNVHQ4EFgQUFam2JN9/9Xo7ebqMDMJZQSu/K2MwDQYJKoZIhvcNAQELBQAD
    ggEBAIWzvXQ8Xmd3mmLVnwxoRraQ3sFYIVYR+iQrTNBYwqsA/3HT0lQQyZKnOiso
    z7mQ3IeFeqkkuf/Ryh+oJIh+5wjwjjs8Qdnq8hKfcbBn3aY69cbwIUztcMC0cVlV
    6dHIb6OuJ9/1P+hXF+khvYpxDUBPUDZebKY9wasZg9c2A0UMWBhiZg4+pr8Lnnys
    ZoVpyltmFKdaH04u8QMut1Ha2dTP3/suTzLiiVVUnpW0Jc7hUMFhbm+pqiX8MbMo
    AFiQe0sbdPtlWtn7wOvJsS30LnEKg4Se0Ixw3A0hqUYg8CvxHpQd6N2QDrNa4ngP
    73MviqD9jU3a/SbDgxBtqdqQ9wU=
    -----END CERTIFICATE-----
